spring:
  datasource:
    url: jdbc:postgresql://ec2-107-20-168-237.compute-1.amazonaws.com:5432/d9aqvf4uj2u55p
    username: wiplhyihvrnwgv
    password: c8e5b5182c6a35864406a9903ecc8b7086567a5a396712a9c1361bfa47622315
    driver-class-name: com.mysql.jbdc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
        tmp.use_jdbc_metadata_defaults: false
        jdbc.lob.non_contextual_creation: true